### PR TITLE
Added mongoose and server startup bindings

### PR DESCRIPTION
**Pull request by Scynes**

### CODE REVIEW

**Comment by Scynes** [comment]
Additional changes added.

**Comment by Scynes** [comment]
Trivia schema is related to what will be written to triviaSets collection.  This is not finalized.

**Comment by Scynes** [comment]
The base API routes are completed.  The routes are literally **/c /r /u /d** to dictate the root level API function. Extending upon this can be completed by implementing APIHandler abstraction and defining sub routes.  This allows a modular design to API.

**Comment by Scynes** [comment]
APIHandler abstraction is nearly complete. These core methods can be fine tuned, but as of now they can be reused across all future API implementations.

**Comment by Scynes** [comment]
Milestone: Finished implementing APIHandler abstract methods and functionality on Trivia API routes.

**Comment by claudiauhr** [comment]
Added changes made by @Scynes

**Pull request merged**
